### ISSUE TITLE
Another issues - Unrecognized function or variable 'finufft'

### ISSUE THREAD

**Issue by Waves-base** [complexphoton/Imaging-simulations#2]
`>> recon_all`
`reconstructing the SMT image with Flatiron nufft: 0%      [          ]Unrecognized function or variable 'finufft'.`
`Error in finufft_plan (line 201)`
`finufft(mex_id_);`
`Error in finufft2d3 (line 52)`
`p = finufft_plan(3,2,isign,n_transf,eps,o);`
`Error in recon_smt (line 102)`
`            Ahr = finufft2d3(single(fy(:)), single(fz(:)), single(R(:)), 1, 1e-2, single(Y(:)), single(Z(:)));`
`Error in recon_all (line 5)`
`recon_smt(data_dir); % reconstruct the SMT image`

**Comment by zywang36** [comment]
Hi Waves-base,

Sorry for the late reply.

It looks like the issue comes from the installation of Flatiron NUFFT. The code finds the finufft2d3 function but cannot find the finufft mex-file. First, make sure that you compile the Matlab interface. After the compilation, there should be a finufft mex-file (https://www.mathworks.com/help/matlab/matlab_external/platform-compatibility.html) under the finufft_x.x.x/matlab directory.  And you should add that directory to the Matlab search path.

Best,
Zeyu
